# Generated by Django 4.2.9 on 2024-01-07 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataentry",
            name="name",
        ),
    ]
